# Generated by Django 4.1.5 on 2023-02-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
