# Generated by Django 4.1.5 on 2023-02-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0002_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': [-1]},
        ),
    ]
