# Generated by Django 4.1.5 on 2023-02-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
