# Generated by Django 4.1.5 on 2023-02-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('content', models.TextField()),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='created_on')),
                ('modifiedon', models.DateTimeField(blank=True, db_column='modified_on', null=True)),
            ],
            options={
                'db_table': 'public_posts',
            },
        ),
    ]
