# Generated by Django 4.1.5 on 2023-02-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0005_publicpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicpost',
            options={'ordering': ['-createdon']},
        ),
        migrations.AddField(
            model_name='publicpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
